spring.application.name=ProductRest
server.port=${PORT:8080}

#Cloudinary Config
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}      
cloudinary.api_key=${CLOUDINARY_API_KEY}            
cloudinary.secret_key=${CLOUDINARY_SECRET_KEY}       

# data-base connectivity -
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
 
#hibernate configuration -
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

